apiVersion: v1
kind: Service
metadata:
  name: devops-platform-active
  namespace: devops-platform
spec:
  selector:
    app: devops-platform
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: devops-platform-preview
  namespace: devops-platform
spec:
  selector:
    app: devops-platform
  ports:
    - port: 80
      targetPort: 3000